language: rust

branches:
  except:
    - /^wip\/.*$/

addons:
  apt:
    packages:
    - cmake
    - curl
    - gcc
    - g++
    - pkg-config
    - binutils-dev
    - libcurl4-openssl-dev
    - zlib1g-dev
    - libdw-dev

install:
- ./tools/install-kcov && source ~/.profile && kcov --version

script:
- cargo test --verbose --manifest-path=src/liblocus/Cargo.toml
- cargo test --verbose --manifest-path=src/libunicode/Cargo.toml
- cargo test --verbose --manifest-path=src/libreader/Cargo.toml
- cargo test --verbose --manifest-path=src/libeval/Cargo.toml
