[package]
name = "libexpand"
version = "0.1.0"
edition = "2018"
authors = ["Sabre developers"]
license = "MIT/Apache-2.0"

[dependencies]
liblocus = { path = "../liblocus", version = "0.1.0" }
libreader = { path = "../libreader", version = "0.1.0" }
